openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/accounts/user:
    get:
      operationId: listUsers
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - api
  /api/accounts/users-recommended:
    get:
      operationId: listusers_recommendeds
      description: "Get users order by followers_count and \nexclude the users that\
        \ the user has followed"
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - api
  /api/post/posts:
    get:
      operationId: listget_posts
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - api
  /:
    get:
      operationId: listSwaggerSchemas
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/coreapi+json:
              schema:
                type: array
                items: {}
            application/openapi+json:
              schema:
                type: array
                items: {}
            text/html:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - ''
  /api/accounts/register:
    post:
      operationId: createUserRegister
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
  /api/accounts/login:
    post:
      operationId: createUserLogin
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
  /api/accounts/follow/{username}:
    post:
      operationId: createfollow_user
      description: ''
      parameters:
      - name: username
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
