# Generated by Django 3.2.2 on 2021-07-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='content',
            field=models.CharField(default='abc', max_length=255),
            preserve_default=False,
        ),
    ]
