# Generated by Django 3.2.2 on 2021-05-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210512_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='Tran Quoc Duy', max_length=200),
            preserve_default=False,
        ),
    ]
