# Generated by Django 3.2.2 on 2021-05-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210513_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_pic',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
